### ISSUE TITLE
怎么启动项目

### ISSUE THREAD

**Issue by cc-qq-gg** [mintsweet/practice#8]
**你是想要一个新的功能*feature*，还是报告一个错误*bug*？**

**预期的结果是什么？**

**当前的结果是什么？**

**如果当前的结果是一个错误，请复现错误流程。**

**如果是一个想要的新的功能，请描述一下为什么想要这个功能？**

**Comment by cc-qq-gg** [comment]
项目怎么启动啊

**Comment by cc-qq-gg** [comment]
项目如何启动m

**Comment by mintsweet** [comment]
文档上面有说哈～

[详见文档](https://docs.mintsweet.cn/#/server)

所有客户端都依赖服务端，先启动`packages/server`包哈
